version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-container
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: api-mysql
    ports:
      - "8181:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: api-phpmyadmin
    environment:
      PMA_HOST: mysql  # même nom que le service mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - 8180:80
    networks:
      - app-network
networks:
  app-network:
    driver: bridge